# Generated by Django 5.2 on 2025-05-10 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='eth_address',
            field=models.CharField(blank=True, max_length=42, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='eth_index',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
