# Generated by Django 5.2 on 2025-05-14 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokensbalances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountbalance',
            old_name='total_balance',
            new_name='hd_wallet_balance',
        ),
    ]
