# Generated by Django 5.2 on 2025-05-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokensbalances', '0002_rename_total_balance_accountbalance_hd_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('ERC20', 'Erc20')], default='ERC20', max_length=10),
        ),
    ]
