# Generated by Django 5.2 on 2025-05-13 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tokensbalances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenpairbasetoken', to='tokensbalances.token')),
                ('pair_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenpairpairtoken', to='tokensbalances.token')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokenpairuser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'active'), ('WAITING_FOR_SETTLEMENT', 'waiting_for_settlement'), ('SETTLED', 'settled'), ('CANCELED', 'canceled')])),
                ('type', models.CharField(choices=[('LIMIT', 'limit'), ('MARKET', 'market')])),
                ('amount', models.BigIntegerField()),
                ('remaining_amount', models.BigIntegerField()),
                ('filled_amount', models.BigIntegerField()),
                ('partially_filled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('locked', models.BooleanField(default=False)),
                ('direction', models.CharField(choices=[('BUY', 'buy'), ('SELL', 'sell')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderuser', to=settings.AUTH_USER_MODEL)),
                ('token_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordertokenpair', to='orders.tokenpair')),
            ],
        ),
    ]
