# Generated by Django 5.2 on 2025-05-14 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('tokensbalances', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tokenpair',
            unique_together={('base_token', 'pair_token')},
        ),
        migrations.RemoveField(
            model_name='tokenpair',
            name='user',
        ),
    ]
