# Generated by Django 5.2 on 2025-05-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_tokenpair_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='limit_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='stop_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='filled_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='remaining_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('WAITING_FOR_SETTLEMENT', 'waiting_for_settlement'), ('SETTLED', 'settled'), ('CANCELED', 'canceled')], default='ACTIVE'),
        ),
    ]
