# Generated by Django 5.2 on 2025-05-14 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_limit_price_order_stop_price_and_more'),
        ('tokensbalances', '0002_rename_total_balance_accountbalance_hd_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='account_balance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ordertokenbalance', to='tokensbalances.accountbalance'),
        ),
    ]
