# Generated by Django 5.2 on 2025-05-14 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_account_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account_balance',
        ),
    ]
