# Generated by Django 5.2 on 2025-05-15 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_account_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('WAITING_FOR_SETTLEMENT', 'waiting_for_settlement'), ('COMPLETED', 'completed'), ('CANCELED', 'canceled')], default='ACTIVE'),
        ),
    ]
