# Generated by Django 5.2 on 2025-05-14 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_account_balance'),
        ('tokensbalances', '0002_rename_total_balance_accountbalance_hd_wallet_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='account_balance',
        ),
        migrations.AddField(
            model_name='order',
            name='other_token_account_balance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orderothertokenaccountbalance', to='tokensbalances.accountbalance'),
        ),
        migrations.AddField(
            model_name='order',
            name='required_token_account_balance',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='orderrequiredtokenaccountbalance', to='tokensbalances.accountbalance'),
        ),
    ]
