# Generated by Django 5.2 on 2025-05-18 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'active'), ('WAITING_FOR_EXECUTION', 'waiting_for_execution'), ('COMPLETED', 'completed'), ('CANCELED', 'canceled')], default='ACTIVE'),
        ),
    ]
