# Generated by Django 5.2 on 2025-05-19 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='direction',
            field=models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('WAITING_FOR_EXECUTION', 'Waiting For Execution'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='ACTIVE'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type',
            field=models.CharField(choices=[('LIMIT', 'Limit'), ('MARKET', 'Market')]),
        ),
    ]
